version: '3.8'  # Ajoutez la version ici pour plus de clarté

services:
  nginx:
    image: nginx:1.22-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/code
      - ./nginx.conf:/etc/nginx/nginx.conf

  php:
    build: .
    volumes:
      - ./:/code

  mysql:
    image: mysql:8.4.1 
    environment:
      MYSQL_ROOT_PASSWORD: limaykongo
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: limaykongo
    ports:
      - "8081:80"  

volumes:
  data:
